### ISSUE TITLE
Property paths

### ISSUE THREAD

**Issue by nvbach91** [hypergraphql/hypergraphql#20]
Hi, I'd like to ask the following:

I have this database
```ttl
 @prefix o: <http://ontology.com/> .
 
 o:Game o:hasName o:Name .
 o:Name o:hasValue "Yu-Gi-Oh!" .
```
I want to query
```graphql
{
  Game {
    name
  }
}
```
to get
```json
...
"data": {
  "Game_GET": [
    {
      "name": "Yu-Gi-Oh!"
    }
  ]
}
...
```
But now, the schema I have is:
```graphql
type __Context {
  Game:     _@href(iri: "http://ontology.com/Game")
  Name:     _@href(iri: "http://ontology.com/Name")
  hasName:  _@href(iri: "http://ontology.com/hasName")
  hasValue: _@href(iri: "http://ontology.com/hasValue")
}

type Game @service(id: "ontology") {
  hasName: Name @service(id: "ontology")
}

type Name @service(id: "ontology") {
  hasValue: String @service(id: "ontology")
}
```
I would have to query
```graphql
{
  Game {
    hasName {
      hasValue
    }
  }
}
```
to get
```json
...
"data": {
  "Game_GET": [
    {
      "hasName": {
        "hasValue": "Yu-Gi-Oh!"
      }
    }
  ]
}
...
```

My question is, how to define the `schema.graphql` so that it make the first GraphQL query possible? Meaning how to chain "hasName"and "hasValue" so it would be reduced to only "name".

I tried
```graphql
type __Context {
  Game:     _@href(iri: "http://ontology.com/Game")
  name:     _@href(iri: "http://ontology.com/hasName" / "http://ontology.com/hasValue")
}
type Game @service(id: "ontology") {
  name: String @service(id: "ontology")
}
```
but no luck.

Thanks for your help

**Comment by pc3356** [comment]
Hi,

A couple of things (all the RDF is in Turtle (TTL) notation):

1) The database you have doesn't really look right for what you're trying to do:
```
@prefix o: <http://ontology.com/> .

o:game1 a o:Game ;
    o:hasName o:name1 .

o:name1 a o:Name ;
    o:hasValue "Yu-Gi-Oh!" .
```

This would probably be better; it deals with specific instances of `Name` and `Game`, and would allow you to extend this further, e.g.:
```
o:game2 a o:Game ;
      o:hasName o:name2.
o:name2 a o:Name ;
     o:hasValue "Chess" .
```

You pretty much specified things at a Class rather than an Instance level in your file, I would expect to see this sort of thing as part of an ontology (this one mixes OWL and RDFS):
```
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix o: <http://ontology/> .

o:Game rdf:type owl:Class .

o:Name rdf:type owl:Class .

o:hasName rdf:type owl:ObjectProperty ;
	rdfs:domain o:Game ;
	rdfs:range o:Name .

o:hasValue rdf:type owl:DatatypeProperty ;
	rdfs:domain o:Name ;
	rdfs:range xsd:string .

```

This states that:
`o:Game is an owl:Class`
`o:Name is a owl:Class`
`o:hasName is an owl:ObjectProperty` i.e. it refers to another class
`o:hasName is a property of o:Game`
`o:hasName has a target of o:Name`
`o:hasValue is an owl:DatatypeProperty` i.e. it refers to a literal value
`o:hasValue is a property of o:Name`
`o:hasValue has a target of type string`

You don't need to define an ontology like this to run your code, this is just an example that could be inferred from it.

2) The mapping `.graphql` file should probably look like this:
```
type __Context {
  Game:     _@href(iri: "http://ontology.com/Game")
  Name:     _@href(iri: "http://ontology.com/Name")
  name:     _@href(iri: "http://ontology.com/hasName")
  value:    _@href(iri: "http://ontology.com/hasValue")
}

type Game @service(id: "ont-local") {
  name: Name @service(id: "ont-local")
}

type Name @service(id: "ont-local") {
  value: String @service(id: "ont-local")
}
```

This would allow you to specify different "shorthand" property names, although there's not currently any support for property paths like you suggested for `o:hasName / o:hasValue` - it's something we should add to our list of TODO items.

3) I think your query should look something like:
```
{
  Game_GET {
    name {
      value
    }
  }
}
```

This will give you:
```
{
  "extensions": {},
  "data": {
    "@context": {
      "_type": "@type",
      "name": "http://ontology.com/hasName",
      "Game_GET": "http://hypergraphql.org/query/Game_GET",
      "_id": "@id",
      "value": "http://ontology.com/hasValue"
    },
    "Game_GET": [
      {
        "name": {
          "value": "Yu-Gi-Oh!"
        }
      }
    ]
  },
  "errors": []
}
```

Which is close to, but maybe not quite exactly, what you were looking for.

I'm hoping to get chance to spend more time on HyperGraphQL in the coming months, and there's certainly a lot of work to be done.

I'm quite interested in the idea of a complete rewrite of the engine into Scala or Kotlin.

Many thanks for your interest, and I hope I've been able to help a little.

**Comment by nvbach91** [comment]
@pc3356 For the sake of simplifying my question, I intentionally made the example source data like that. In my real database, the data are nested even more than that, so I thought property paths could help flatten the structure of the query output. 

Thanks for the extensive answer, it proves to me that you and I are on the same page. I needed to know if this property paths feature was in dev. Now that I'm certain, I too might take a look and come up with a PR myself. I hope everybody can see property paths coming soon.
