### ISSUE TITLE
Dangling Release Note in README.md

### ISSUE THREAD

**Issue by soblinger** [hypergraphql/hypergraphql#7]
The [README.md](https://github.com/hypergraphql/hypergraphql/blob/master/README.md) contains a note about Release v1.1.4, but there are only Release versions 0.1 and 0.2 available. This is confusing.

**Comment by pc3356** [comment]
Yes, this is true; we were going to make this release and then had to stop it. We will use a sensible version number, probably 1.0.0, for the forthcoming release, which will provide an executable JAR and external configuration, so that it's no longer necessary to build the application from sources.

We have also identified and fixed all the typos and inaccuracies in the documentation.
